(cl:defpackage my_custom_src_msg_pkg-srv
  (:use )
  (:export
   "CUSTOMDURATIONMESSAGE"
   "<CUSTOMDURATIONMESSAGE-REQUEST>"
   "CUSTOMDURATIONMESSAGE-REQUEST"
   "<CUSTOMDURATIONMESSAGE-RESPONSE>"
   "CUSTOMDURATIONMESSAGE-RESPONSE"
   "MYCUSTOMSERVICEMESSAGE"
   "<MYCUSTOMSERVICEMESSAGE-REQUEST>"
   "MYCUSTOMSERVICEMESSAGE-REQUEST"
   "<MYCUSTOMSERVICEMESSAGE-RESPONSE>"
   "MYCUSTOMSERVICEMESSAGE-RESPONSE"
  ))

