(cl:defpackage my_turtlebot_actions-msg
  (:use )
  (:export
   "<RECORD_ODOMACTION>"
   "RECORD_ODOMACTION"
   "<RECORD_ODOMACTIONFEEDBACK>"
   "RECORD_ODOMACTIONFEEDBACK"
   "<RECORD_ODOMACTIONGOAL>"
   "RECORD_ODOMACTIONGOAL"
   "<RECORD_ODOMACTIONRESULT>"
   "RECORD_ODOMACTIONRESULT"
   "<RECORD_ODOMFEEDBACK>"
   "RECORD_ODOMFEEDBACK"
   "<RECORD_ODOMGOAL>"
   "RECORD_ODOMGOAL"
   "<RECORD_ODOMRESULT>"
   "RECORD_ODOMRESULT"
  ))

