// Generated by gencpp from file my_sphero_actions/record_odomResult.msg
// DO NOT EDIT!


#ifndef MY_SPHERO_ACTIONS_MESSAGE_RECORD_ODOMRESULT_H
#define MY_SPHERO_ACTIONS_MESSAGE_RECORD_ODOMRESULT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <nav_msgs/Odometry.h>

namespace my_sphero_actions
{
template <class ContainerAllocator>
struct record_odomResult_
{
  typedef record_odomResult_<ContainerAllocator> Type;

  record_odomResult_()
    : result_odom_array()  {
    }
  record_odomResult_(const ContainerAllocator& _alloc)
    : result_odom_array(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::nav_msgs::Odometry_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::nav_msgs::Odometry_<ContainerAllocator> >::other >  _result_odom_array_type;
  _result_odom_array_type result_odom_array;





  typedef boost::shared_ptr< ::my_sphero_actions::record_odomResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::my_sphero_actions::record_odomResult_<ContainerAllocator> const> ConstPtr;

}; // struct record_odomResult_

typedef ::my_sphero_actions::record_odomResult_<std::allocator<void> > record_odomResult;

typedef boost::shared_ptr< ::my_sphero_actions::record_odomResult > record_odomResultPtr;
typedef boost::shared_ptr< ::my_sphero_actions::record_odomResult const> record_odomResultConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::my_sphero_actions::record_odomResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::my_sphero_actions::record_odomResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace my_sphero_actions

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'nav_msgs': ['/opt/ros/kinetic/share/nav_msgs/cmake/../msg'], 'my_sphero_actions': ['/home/user/catkin_ws/devel/share/my_sphero_actions/msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::my_sphero_actions::record_odomResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::my_sphero_actions::record_odomResult_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::my_sphero_actions::record_odomResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::my_sphero_actions::record_odomResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_sphero_actions::record_odomResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_sphero_actions::record_odomResult_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::my_sphero_actions::record_odomResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "92760902640d743b2b3ea16a1270021c";
  }

  static const char* value(const ::my_sphero_actions::record_odomResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x92760902640d743bULL;
  static const uint64_t static_value2 = 0x2b3ea16a1270021cULL;
};

template<class ContainerAllocator>
struct DataType< ::my_sphero_actions::record_odomResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "my_sphero_actions/record_odomResult";
  }

  static const char* value(const ::my_sphero_actions::record_odomResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::my_sphero_actions::record_odomResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
#result, Odometry array\n\
nav_msgs/Odometry[] result_odom_array\n\
\n\
================================================================================\n\
MSG: nav_msgs/Odometry\n\
# This represents an estimate of a position and velocity in free space.  \n\
# The pose in this message should be specified in the coordinate frame given by header.frame_id.\n\
# The twist in this message should be specified in the coordinate frame given by the child_frame_id\n\
Header header\n\
string child_frame_id\n\
geometry_msgs/PoseWithCovariance pose\n\
geometry_msgs/TwistWithCovariance twist\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: geometry_msgs/PoseWithCovariance\n\
# This represents a pose in free space with uncertainty.\n\
\n\
Pose pose\n\
\n\
# Row-major representation of the 6x6 covariance matrix\n\
# The orientation parameters use a fixed-axis representation.\n\
# In order, the parameters are:\n\
# (x, y, z, rotation about X axis, rotation about Y axis, rotation about Z axis)\n\
float64[36] covariance\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Pose\n\
# A representation of pose in free space, composed of position and orientation. \n\
Point position\n\
Quaternion orientation\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Quaternion\n\
# This represents an orientation in free space in quaternion form.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
float64 w\n\
\n\
================================================================================\n\
MSG: geometry_msgs/TwistWithCovariance\n\
# This expresses velocity in free space with uncertainty.\n\
\n\
Twist twist\n\
\n\
# Row-major representation of the 6x6 covariance matrix\n\
# The orientation parameters use a fixed-axis representation.\n\
# In order, the parameters are:\n\
# (x, y, z, rotation about X axis, rotation about Y axis, rotation about Z axis)\n\
float64[36] covariance\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Twist\n\
# This expresses velocity in free space broken into its linear and angular parts.\n\
Vector3  linear\n\
Vector3  angular\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Vector3\n\
# This represents a vector in free space. \n\
# It is only meant to represent a direction. Therefore, it does not\n\
# make sense to apply a translation to it (e.g., when applying a \n\
# generic rigid transformation to a Vector3, tf2 will only apply the\n\
# rotation). If you want your data to be translatable too, use the\n\
# geometry_msgs/Point message instead.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
";
  }

  static const char* value(const ::my_sphero_actions::record_odomResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::my_sphero_actions::record_odomResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.result_odom_array);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct record_odomResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::my_sphero_actions::record_odomResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::my_sphero_actions::record_odomResult_<ContainerAllocator>& v)
  {
    s << indent << "result_odom_array[]" << std::endl;
    for (size_t i = 0; i < v.result_odom_array.size(); ++i)
    {
      s << indent << "  result_odom_array[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::nav_msgs::Odometry_<ContainerAllocator> >::stream(s, indent + "    ", v.result_odom_array[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // MY_SPHERO_ACTIONS_MESSAGE_RECORD_ODOMRESULT_H
